services:
  store-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: klavisha
      POSTGRES_PASSWORD: klavisha_password
      POSTGRES_DB: store_db
    ports:
      - "5432:5432"
    volumes:
      - store-db-data:/var/lib/postgresql/data

volumes:
  store-db-data:
